name:                osmesa-analytics-server
version:             0.1.0.0
synopsis:            Produce random OSMesa query data.
description:         Produce random OSMesa query data.
homepage:            https://github.com/fosskers/osmesa-analytics-server
license:             BSD3
author:              Colin Woodbury
maintainer:          cwoodbury@azavea.com
copyright:           2017 Azavea
category:            Web

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.1 && < 1.3
  - aeson-pretty
  - bytestring
  - containers
  - generic-random >= 1.0 && < 1.1
  - http-types >= 0.9 && < 0.10
  - QuickCheck >= 2.9 && < 2.11
  - servant >= 0.11 && < 0.12
  - servant-docs >= 0.11 && < 0.12
  - servant-server >= 0.11 && < 0.12
  - text
  - time
  - wai >= 3.2 && < 3.3
  - warp >= 3.2 && < 3.3

executables:
  server:
    source-dirs:      src
    main:             Server.hs
