name:                osmesa-analytics-server
version:             0.1.0.0
synopsis:            Produce random OSMesa query data.
description:         Produce random OSMesa query data.
homepage:            https://github.com/fosskers/osmesa-analytics-server
license:             BSD3
author:              Colin Woodbury
maintainer:          cwoodbury@azavea.com
copyright:           2017 Azavea
category:            Web

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.1 && < 1.3
  - aeson-pretty
  - containers
  - generic-random >= 1.0 && < 1.1
  - QuickCheck >= 2.9 && < 2.11
  - text
  - time

executables:
  server:
    source-dirs:      src
    main:             Server.hs
